#spring:
#  application:
#    name: ProjectTraninng
#  datasource:
#    url: jdbc:mysql://localhost:3304/MedicalComplexDB
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: #AbuThaher12345
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    servlet:
#      multipart:
#        enabled: true
#        max-file-size: 10MB
#        max-request-size: 10MB
#    mail:
#      host: smtp.gmail.com
#      port: 587
#      username: mohammadmashhour24@gmail.com
#      password: fzkq khke mbxe yukj
#      properties:
#        mail.smtp.auth: true
#        mail.smtp.starttls.enable: true
#
#  application:
#    security:
#      jwt:
#        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#        expiration: 86400000
#        refresh-token:
#          expiration: 604800000
#
#  logging:
#    level:
#      root: INFO
#      com.example: DEBUG
#
#  server:
#    port: 8080
